### ISSUE TITLE
Tables need to be paginated

### ISSUE THREAD

**Issue by mvl22** [DoccyB/cycledata#1]
Currently the tables list everything, which can be quite a long listing, that could crash the browser.

It would be useful if the tables were paginated, so that users can click between pages.

**Comment by DoccyB** [comment]
Thanks for the feedback Martin!

You should now be able to navigate through the tables by page number.

**Comment by mvl22** [comment]
Great! See the comment I've just submitted about a further change.

See also if you can add a `<` and `>` symbol which links to the previous/next page. Obviously it will need to work out what those are at any time.

**Comment by DoccyB** [comment]
Where is this comment?

Managed to implement the previous/next page buttons, although haven't fixed
an upper/lower limit yet.

Clocking off now, thanks for today!
